# Generated by Django 5.0.6 on 2024-05-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('eghtesadi', 'اقتصادی'), ('siasi', 'سیاسی'), ('varzeshi', 'ورزشی'), ('ostani', 'استانی')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
