# Generated by Django 5.0.6 on 2024-06-01 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_messenger_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('movie', models.FileField(upload_to='images/Article/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('category', models.CharField(choices=[('eghtesadi', 'اقتصادی'), ('siasi', 'سیاسی'), ('varzeshi', 'ورزشی'), ('ostani', 'استانی')], max_length=15)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
