# Generated by Django 5.0.6 on 2024-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/Article/'),
        ),
    ]
